<?php

/**
 * @file
 * Contains standup.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function standup_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the standup module.
    case 'help.page.standup':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Example') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function standup_theme() {
  return [
    'standup' => [
      'render element' => 'children',
    ],
  ];
}
