<?php

/**
 * @file
 * Contains sandwich.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function sandwich_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the sandwich module.
    case 'help.page.sandwich':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Pluggable Sandwich module') . '</p>';
      return $output;

    default:
  }
}
